project:
  type: website
  output-dir: docs

website:
  title: "Torrents of Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhackmeister
      - icon: globe
        href: https://bsky.app/profile/jhackmeister.bsky.social
      - icon: envelope
        href: mailto:j_hackmeister@gmail.com
page-footer:
    center: |
      Torrents of Data Â· Built with [Quarto](https://quarto.org/)
    background: "primary"
format:
  html:
    theme: 
      light: [cosmo, custom.scss]
editor: visual 