project:
  type: website
  output-dir: docs

website:
  title: "Torrents of Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhackmeister
      - icon: globe
        href: https://bsky.app/profile/jhackmeister.bsky.social
format:
  html:
    theme: Minty
    css: styles.css

editor: visual